.\"	$MirOS: src/usr.bin/calendar/calendar.1,v 1.11 2021/10/29 02:24:22 tg Exp $
.\"	$OpenBSD: calendar.1,v 1.29 2005/03/22 10:57:27 xsa Exp $
.\"
.\" Copyright (c) 1989, 1990, 1993
.\"     The Regents of the University of California.  All rights reserved.
.\" Copyright (c) 2019, 2021
.\"	mirabilos <m@mirbsd.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)calendar.1  8.1 (Berkeley) 6/29/93
.\"
.Dd $Mdocdate: October 29 2021 $
.Dt CALENDAR 1
.Os
.Sh NAME
.Nm calendar
.Nd reminder service
.Sh SYNOPSIS
.Nm calendar
.Op Fl ab
.Op Fl A Ar num
.Op Fl B Ar num
.Op Fl f Ar calendarfile
.Op Fl t Ar [[[cc]yy][mm]]dd
.Sh DESCRIPTION
The
.Nm
utility checks the current directory or the directory specified by the
.Ev CALENDAR_DIR
environment variable for a file named
.Pa Li calendar
and displays lines that begin with either today's date
or tomorrow's.
On Fridays, events on Friday through Monday are displayed.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A Ar num
Print lines from today and next
.Ar num
days (forward, future).
.It Fl a
Process the
.Dq Li calendar
files of all users and mail the results
to them.
This requires superuser privileges.
.It Fl B Ar num
Print lines from today and previous
.Ar num
days (backward, past).
.It Fl b
Enforce special date calculation mode for Cyrillic calendars.
.It Fl f Pa calendarfile
Use
.Pa calendarfile
.Pq So Li \-\& Sc for stdin
as the default calendar file.
.It Fl t Ar [[[cc]yy][mm]]dd
Act like the specified value is
.Dq today
instead of using the current date.
.El
.Pp
To handle calendars in different encodings, specify
.Dq LANG=<locale_name>
in the calendar file as early as possible.
That being said, there are no locales on
.Mx
so
.Nm
handles
.Ar locale_name
as
.Ar country Ns Li . Ns Ar encoding ;
.Ar country
is used to make some special handling available, and
.Ar encoding
is used to convert the entries to UTF-8.
.Pp
National names for special days can be handled by adding lines such as
.Dq Advent=<national_name>
(for the Western Church first Sunday of Advent),
.Dq Easter=<national_name>
(for Catholic Easter),
.Dq Paskha=<national_name>
(for Orthodox Easter) or
.Dq Pesach=<national_name>
(for Jewish Passover),
setting the corresponding variables.
.Pp
The
.Dq CALENDAR
variable can be used to specify the style.
Only
.Sq Julian
and
.Sq Gregorian
styles are currently supported.
Use
.Dq CALENDAR=
to return to the default (Gregorian).
.Pp
To enforce special date calculation mode for Cyrillic calendars
specify
.Dq LANG=<locale_name>
and
.Dq BODUN=<bodun_prefix>
where <locale_name> can be
.Li ru_RU.KOI8\-R ,
.Li uk_UA.KOI8\-U ,
.Li by_BY.KOI8\-B
or their
.Li .UTF\-8
counterparts.
.Pp
To enable specific anniversary handling, applied to all complete
event texts that start with a four-digit year plus comma and space,
or that end with comma and space and a four-digit year,
appending a formatted text instead, set
.Dq ANNIV=<ago_text><us><cur_text><us><future_text>
(where
.Ic us
is the ASCII unit separator (Ctrl-_, 0x1F) and the texts are used
if the event happened in the past, present or future, respectively;
.Dq "%1$d"
and
.Dq "%2$d"
in the texts are replaced by the year and the absolute year delta
respectively),
.Em or
use
.Dq ANNIV=1
which enables this mode using the default
.Dq "%1$d: %2$d year(s) ago",
.Dq "%1$d: this year" ,
.Dq "%1$d: in %2$d year(s)"
if none are specified otherwise.
Some crazy Russian formats are also parsed,
conflating "\-e" ('s) and "G" (year), ignoring "do n.e." (BCE).
.Pp
Other lines should begin with a month and day.
They may be entered in almost any format, either numeric or as character
strings.
If proper locale is set, national months and weekdays
names can be used (not on
.Mx
which does not support locales).
A single asterisk
.Pq Sq *\&
matches every month.
A day without a month matches that day of every week.
A month without a day matches the first of that month.
Two numbers default to the month followed by the day.
Lines with leading tabs default to the last entered date, allowing
multiple line specifications for a single date.
.Ic Advent ,
.Ic Easter ,
.Ic Paskha
and
.Ic Pesach ,
both these standard English and the user-defined national (see above) names,
correspond to the respective special day for this year; they may be followed
by a positive (with an explicit
.Ql +\& )
or negative integer to offset the day.
Weekday names may be followed by
.Dq \-4
.Li ...
.Dq +5
(aliases last, first, second, third, fourth) for moving events like
.Dq the last Monday in April .
.Pp
By convention, dates followed by an asterisk
.Pq Sq *\&
are not fixed, i.e.\& change from year to year.
.Pp
Day descriptions start after the first <tab> character in the line;
if the line does not contain a <tab> character, it isn't printed out.
If the first character in the line is a <tab> character, it is treated as
the continuation of the previous description.
.Pp
The calendar file is preprocessed by
.Xr cpp 1 ,
allowing the inclusion of shared files such as company holidays or
meetings.
If the shared file is not referenced by a full pathname,
.Xr cpp 1
searches in the current (or home) directory first, and then in the
directory
.Pa /usr/share/calendar .
Empty lines and C comments
.Pq Li /* ... */
are ignored.
.Pp
Some possible calendar entries
(a \fB\et\fR sequence denotes a <tab> character):
.Bd -unfilled -offset indent
LANG=C
Easter=Ostern

#include <calendar.usholiday>
#include <calendar.birthday>

6/15\fB\et\fRJune 15 (if ambiguous, will default to month/day).
Jun. 15\fB\et\fRJune 15.
15 June\fB\et\fRJune 15.
Thursday\fB\et\fREvery Thursday.
June\fB\et\fREvery June 1st.
15 *\fB\et\fR15th of every month.

May Sun+2\fB\et\fRsecond Sunday in May (Muttertag)
04/SunLast\fB\et\fRlast Sunday in April,
\fB\et\fRsummer time in Europe
Easter\fB\et\fREaster
Ostern\-2\fB\et\fRGood Friday (2 days before Easter)
Paskha\fB\et\fROrthodox Easter
Advent+21\fB\et\fR4th Sunday of Advent
.Ed
.Sh FILES
.Bl -tag -width ~/.etc/calendar/calendar -compact
.It Pa calendar
File in current directory.
.It Pa ~/.etc/calendar
Directory in the user's home directory (which
.Nm
changes into, if it exists).
.It Pa ~/.etc/calendar/calendar
File to use if no
.Pa calendar
file exists in the current directory.
.It Pa ~/.etc/calendar/nomail
.Nm
will not mail if this file exists.
.It Pa calendar.all
International and national calendar files.
.It Pa calendar.birthday
Births and deaths of famous (and not-so-famous) people.
.It Pa calendar.christian
Christian holidays (should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year).
.It Pa calendar.computer
Computer people's days of special significance.
.It Pa calendar.croatian
Croatian calendar.
.It Pa calendar.fictional
Fantasy and fiction dates (mostly LOTR).
.It Pa calendar.french
French calendar.
.It Pa calendar.german
German calendar.
.It Pa calendar.history
Everything else, mostly U.S. historical events.
.It Pa calendar.holiday
Other holidays (including the not-well-known, obscure, and
.Em really
obscure).
.It Pa calendar.judaic
Jewish holidays (should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year).
.It Pa calendar.music
Musical events, births, and deaths (strongly oriented toward rock'n'roll).
.It Pa calendar.openbsd
.Ox
and
.Mx
related events.
.It Pa calendar.pagan
Pagan holidays, celebrations and festivals.
.It Pa calendar.russian
Russian calendar.
.It Pa calendar.usholiday
U.S. holidays.
.It Pa calendar.world
World wide calendar.
.El
.Sh SEE ALSO
.Xr at 1 ,
.Xr cal 1 ,
.Xr cpp 1 ,
.Xr mail 1 ,
.Xr cron 8
.Sh STANDARDS
The
.Nm
program previously selected lines which had the correct date anywhere
in the line.
This is no longer true: the date is only recognised when it occurs
at the beginning of a line.
.Sh HISTORY
A
.Nm
command appeared in
.At v7 .
.Pp
Since
.Mx 10 ,
if the
.Dv UNICODE
variable is set during compilation,
.Xr iconv 3
is used to convert any input to UTF-8 output.
.Pp
.Dv ANNIV
and
.Ic Advent
handling appeared in
.Mx 11 .
Other implementations silently ignore the field assignment,
so
.Dv ANNIV
is backwards-compatible.
.Sh BUGS
.Nm
doesn't handle all Jewish holidays or moon phases.
