.\"	$MirOS: src/usr.bin/calendar/calendar.1,v 1.22 2024/01/05 02:09:00 tg Exp $
.\"	$OpenBSD: calendar.1,v 1.29 2005/03/22 10:57:27 xsa Exp $
.\"
.\" Copyright (c) 1989, 1990, 1993
.\"     The Regents of the University of California.  All rights reserved.
.\" Copyright © 2019, 2021, 2023
.\"	mirabilos <m@mirbsd.org>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     @(#)calendar.1  8.1 (Berkeley) 6/29/93
.\"
.\"-
.\" $miros: contrib/samples/portmdoc,v 1.23 2024/01/04 22:52:50 tg Exp $
.\"-
.\" Copyright © 2008, 2009, 2010, 2016, 2018, 2020, 2023
.\"	mirabilos <m@mirbsd.org>
.\"
.\" Glue GNU groff (BSD and GNU mdoc both) to AT&T nroff (UCB mdoc).
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en for a solo en dash
.\" *   and \*(EM for a correctly spaced em dash
.\" * <>| are problematic, so redefine and use \*(Lt\*(Gt\*(Ba
.\" Also make sure to use \& *before* a punctuation char that is to not
.\" be interpreted as punctuation, and especially with two-letter words
.\" but also (after) a period that does not end a sentence (“e.g.\&”).
.\"-
.\"
.\" Implement .Dd with the Mdocdate RCS keyword
.\"
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3
..
.\"
.\" .Dd must come before most everything, because when called
.\" with -mandoc it loads -mdoc via .so in .Dd (first macro).
.\"
.Dd $Mdocdate: January 5 2024 $
.\"
.\" Check which macro package we use, and do other -mdoc setup.
.\"
.ie \n(.g \{\
.	if n .ss \n[.ss] 0
.	if \*[.T]ascii .tr \-\N'45'
.	if \*[.T]latin1 .tr \-\N'45'
.	if \*[.T]utf8 .tr \-\N'45'
.	if \*[.T]utf8 .tr \(la\*(Lt
.	if \*[.T]utf8 .tr \(ra\*(Gt
.	ds <= \(<=
.	ds >= \(>=
.	ds Rq \(rq
.	ds Lq \(lq
.	ds sL \(aq
.	ds sR \(aq
.	if \*[.T]utf8 .ds sL `
.	if \*[.T]ps .ds sL `
.	if \*[.T]utf8 .ds sR '
.	if \*[.T]ps .ds sR '
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.	ie d volume-ds-1 .ds tT gnu
.	el .ie d doc-volume-ds-1 .ds tT gnp
.	el .ds tT bsd
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.	ds tT ucb
.\}
.ie n \{\
.	ds EM \ \(em\ \&
.\}
.el \{\
.	ds EM \f(TR\|\(em\|\fP
.\}
.\"
.\" Add UCB mdoc compatibility to GNU mdoc
.\" Implement .Mx (MirBSD)
.\"
.ie "\*(tT"gnu" \{\
.	ds sP \s0
.	ds tN \*[Tn-font-size]
.	eo
.	de Mx
.	nr curr-font \n[.f]
.	nr curr-size \n[.ps]
.	ds str-Mx \f[\n[curr-font]]\s[\n[curr-size]u]
.	ds str-Mx1 \*(tN\%MirBSD\*[str-Mx]
.	if !\n[arg-limit] \
.	if \n[.$] \{\
.	ds macro-name Mx
.	parse-args \$@
.	\}
.	if (\n[arg-limit] > \n[arg-ptr]) \{\
.	nr arg-ptr +1
.	ie (\n[type\n[arg-ptr]] == 2) \
.	ds str-Mx1 \*(tN\%MirBSD\~#\*[arg\n[arg-ptr]]\*[str-Mx]
.	el \
.	nr arg-ptr -1
.	\}
.	ds arg\n[arg-ptr] "\*[str-Mx1]
.	nr type\n[arg-ptr] 2
.	ds space\n[arg-ptr] "\*[space]
.	nr num-args (\n[arg-limit] - \n[arg-ptr])
.	nr arg-limit \n[arg-ptr]
.	if \n[num-args] \
.	parse-space-vector
.	print-recursive
..
.	de Aq
.	if !\n[arg-limit] \
.	ds macro-name Aq
.	ie \n[in-authors-section] \{\
.		ds quote-left \*(Lt
.		ds quote-right \*(Gt
.	\}
.	el \{\
.		ds quote-left \[la]
.		ds quote-right \[ra]
.	\}
.	enclose-string \$@
..
.	ec
.\}
.el .ie "\*(tT"gnp" \{\
.	ds sP \s0
.	ie t .ds tN \s[(\n[.ps]u-1z)]
.	el .ds tN
.	eo
.	de Mx
.	nr doc-curr-font \n[.f]
.	nr doc-curr-size \n[.ps]
.	ds doc-str-Mx \f[\n[doc-curr-font]]\s[\n[doc-curr-size]u]
.	ds doc-str-Mx1 \*(tN\%MirBSD\*[doc-str-Mx]
.	if !\n[doc-arg-limit] \
.	if \n[.$] \{\
.	ds doc-macro-name Mx
.	doc-parse-args \$@
.	\}
.	if (\n[doc-arg-limit] > \n[doc-arg-ptr]) \{\
.	nr doc-arg-ptr +1
.	ie (\n[doc-type\n[doc-arg-ptr]] == 2) \
.	ds doc-str-Mx1 \*(tN\%MirBSD\~#\*[doc-arg\n[doc-arg-ptr]]\*[doc-str-Mx]
.	el \
.	nr doc-arg-ptr -1
.	\}
.	ds doc-arg\n[doc-arg-ptr] "\*[doc-str-Mx1]
.	nr doc-type\n[doc-arg-ptr] 2
.	ds doc-space\n[doc-arg-ptr] "\*[doc-space]
.	nr doc-num-args (\n[doc-arg-limit] - \n[doc-arg-ptr])
.	nr doc-arg-limit \n[doc-arg-ptr]
.	if \n[doc-num-args] \
.	doc-parse-space-vector
.	doc-print-recursive
..
.	ec
.\}
.el \{\
.	de Mx
.	nr cF \\n(.f
.	nr cZ \\n(.s
.	ds aa \&\f\\n(cF\s\\n(cZ
.	if \\n(aC==0 \{\
.		ie \\n(.$==0 \&\\*(tNMirBSD\\*(aa
.		el .aV \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8 \\$9
.	\}
.	if \\n(aC>\\n(aP \{\
.		nr aP \\n(aP+1
.		ie \\n(C\\n(aP==2 \{\
.			nr xX 0
.			nr xX 1+\\*(A\\n(aP
.			as b1 \&\\*(tNMirBSD\ \&
.			if \\n(xX>0 .as b1 #\&
.			as b1 \&\\*(A\\n(aP\\*(aa
.			rr xX
.			ie \\n(aC>\\n(aP \{\
.				nr aP \\n(aP+1
.				nR
.			\}
.			el .aZ
.		\}
.		el \{\
.			as b1 \&\\*(tNMirBSD\\*(aa
.			nR
.		\}
.	\}
..
.\}
.\" </MirCVS://contrib/samples/portmdoc>
.\"-
.Dt CALENDAR 1
.Os
.Sh NAME
.Nm calendar
.Nd reminder service
.Sh SYNOPSIS
.Bk -words
.Nm calendar
.Op Fl abP
.Op Fl A Ar num
.Op Fl B Ar num
.Op Fl D Ar macro Ns Op Ar =defn
.Op Fl f Ar calendarfile
.Op Fl I Ar dir
.Op Fl t Ar [[[cc]yy][mm]]dd
.Ek
.Sh DESCRIPTION
The
.Nm
utility checks the current directory or the directory specified by the
.Ev CALENDAR_DIR
environment variable for a file named
.Pa calendar
and displays lines that begin with either today's date
or tomorrow's.
On Fridays, events on Friday through Monday are displayed.
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Fl A Ar num
Print lines from today and next
.Ar num
days (forward, future).
.It Fl a
Process the
.Dq Li calendar
files of all users and mail the results
to them.
This requires superuser privileges.
.It Fl B Ar num
Print lines from today and previous
.Ar num
days (backward, past).
.It Fl b
Enforce special date calculation mode for Cyrillic calendars.
.It Fl D Ar macro Ns Op Ar =defn
Passed on to
.Xr cpp 1 ,
for
.Li #ifdef
etc.\& in the calendar file.
.It Fl f Ar calendarfile
Use
.Ar calendarfile
.Pq So Li \-\& Sc for stdin
as the default calendar file.
.It Fl I Ar dir
Passed on to
.Xr cpp 1 ,
for
.Li #include
in the calendar file.
.It Fl P
Parse the entire calendar file and convert it to an output format
intended to be consumed by calendar format conversion utilities,
representing the information from the original entries including
year and time-of-day extensions (see below).
When given twice, the original first line is also quoted before
each event heading.
.It Fl t Ar [[[cc]yy][mm]]dd
Act like the specified value is
.Dq today
instead of using the current date.
.El
.Pp
To handle calendars in different encodings, specify
.Dq LANG=<locale_name>
in the calendar file as early as possible.
That being said, there are no locales on
.Mx
so
.Nm
handles
.Ar locale_name
as
.Ar country Ns Li . Ns Ar encoding ;
.Ar country
is used to make some special handling available, and
.Ar encoding
is used to convert the entries to UTF-8.
.Pp
National names for special days can be handled by adding lines such as
.Dq Advent=<national_name>
(for the Western Church first Sunday of Advent),
.Dq Easter=<national_name>
(for Catholic Easter),
.Dq Paskha=<national_name>
(for Orthodox Easter) or
.Dq Pesach=<national_name>
(for Jewish Passover),
setting the corresponding variables.
.Pp
The
.Dq CALENDAR
variable can be used to specify the style.
Only
.Sq Julian
and
.Sq Gregorian
styles are currently supported.
Use
.Dq CALENDAR=
to return to the default (Gregorian).
.Pp
To enforce special date calculation mode for Cyrillic calendars
specify
.Dq LANG=<locale_name>
and
.Dq BODUN=<bodun_prefix>
where <locale_name> can be
.Li ru_RU.KOI8\-R ,
.Li uk_UA.KOI8\-U ,
.Li by_BY.KOI8\-B
or their
.Li .UTF\-8
counterparts.
.Pp
To enable specific anniversary handling, applied to all complete
event texts that start with a four-digit year plus comma and space,
or that end with comma and space and a four-digit year,
appending a formatted text instead, set
.Dq ANNIV=<ago_text><us><cur_text><us><future_text>
(where
.Ic us
is the ASCII unit separator (Ctrl-_, 0x1F) and the texts are used
if the event happened in the past, present or future, respectively;
.Dq "%1$d"
and
.Dq "%2$d"
in the texts are replaced by the year and the absolute year delta
respectively),
.Em or
use
.Dq ANNIV=1
which enables this mode using the default
.Dq "%1$d: %2$d year(s) ago",
.Dq "%1$d: this year" ,
.Dq "%1$d: in %2$d year(s)"
if none are specified otherwise.
Some crazy Russian formats are also parsed,
conflating "\-e" ('s) and "G" (year), ignoring "do n.e." (BCE).
.Pp
Other lines should begin with a month and day.
They may be entered in almost any format, either numeric or as character
strings.
If proper locale is set, national months and weekdays
names can be used (not on
.Mx
which does not support locales).
A single asterisk
.Pq Sq *\&
matches every month.
A day without a month matches that day of every week.
A month without a day matches the first of that month.
Two numbers default to the month followed by the day.
Lines with leading tabs default to the last entered date, allowing
multiple line specifications for a single date.
.Ic Advent ,
.Ic Easter ,
.Ic Paskha
and
.Ic Pesach ,
both these standard English and the user-defined national (see above) names,
correspond to the respective special day for this year; they may be followed
by a positive (with an explicit
.Ql +\& )
or negative integer to offset the day.
Weekday names may be followed by
.Dq \-4
.Li ...\&
.Dq +5
(aliases last, first, second, third, fourth) for moving events like
.Dq the last Monday in April .
.Pp
By convention, dates followed by an asterisk
.Pq Sq *\&
are not fixed, i.e.\& change from year to year.
.Pp
Day descriptions start after the first <tab> character in the line;
if the line does not contain a <tab> character, it isn't printed out.
If the first character in the line is a <tab> character, it is treated as
the continuation of the previous description.
.Pp
Day descriptions may begin with a four-digit year (between 1000 and 2999)
followed by a comma and space, and/or a time-of-day descriptor followed
by a space (in either case, at least one other character is required).
This is mostly useful in
.Fl P
.Pq conversion
mode, but the leading year is picked up by anniversary processing
.Pq see above
as well, and the user may appreciate this information anyway.
A time-of-day specification shall be
.Xo
.Ar starttime Ns Oo Ic dash Ns Oo
.Ar endtime Oc Oc Ns Oo Ic open-bracket
.Ar timezone Ic close-bracket Oc
.Xc
where
.Ar starttime
and
.Ar endtime
are 24-hour specifications (e.g.\& 01:23),
.Ic dash
is either ASCII
.Ql \-\&
hyphen-minus or U+2013 EN DASH),
.Ic open-bracket No is Ql [\& ,
.Ic close-bracket No is Ql ]\&
and
.Ar timezone
is an Olson tzdata identifier.
24-hour specifications go from 00:00 to 23:59; 24:00 is additionally
recognised but mapped to 23:59 so events stay within one day.
.Pp
The parse-and-extract mode output format is as follows,
suppressing the normal output:
.Bl -tag -width Ds
.It \(dg quoted original line
If
.Fl PP
is used, the original first line of an event specification (the one
that does not start with a tab), prefixed by
.Ql \*(Gt ,
is output first (unchanged but preprocessed).
.It \(dg metadata line (event heading)
This line is comprised of the following fields:
.Bl -tag -width Ds
.It variable-day marker
Either an asterisk
.Ql *\&
(if
.Nm
would otherwise have printed one) or an equals sign
.Ql =\& .
This field, unlike all others, is not followed by a space.
.It date
YYYY\-MM\-DD formatted date of either the first occurrence within
a given year, if a year is part of the extended day description
.Pq see above ,
or the next occurrence after or starting with
.Dq today
.Pq see above .
.It recurrence mode
This is normally one of
.Ic yearly ,
.Ic monthly
or
.Ic weekly .
Yearly events with a given year in the extended day description change to
.Ic once .
Events whose days are based on a special calculation (Advent, Easter, etc.) are
.Ic special
instead, independent on whether they would occur once or yearly.
.It recurrence frequency
Special events show the English name (Advent, Easter, Paskha, Pesach),
followed by either a plus or minus, and a number (offset in days).
Yearly and once events show
.Ic \-mm\-dd
or
.Ic \-mm,www+n
where
.Ar mm
is the month number (01 to 12),
.Ar dd
is the day number (01 to 31),
.Ar www
is the weekday (Sun, Mon, Tue, Wed, Thu, Fri, Sat), and
.Ar +n
is either plus or minus and a number, showing the first (+1),
second (+2), etc.\& or last (\-1), penultimate (\-2), etc.\&
occurrence of the given weekday in a month.
Monthly events show
.Ic dd
if they recur on the same day-of-month number, and
.Ar www+n
if they recur on one given weekday each month.
Weekly events show
.Ic www .
.It year
Either an asterisk
.Pq Ql *\&
or a four-digit year number.
.It start and end times and timezone
This is either one field, literally
.Ic whole-day ,
or two fields, optionally followed by a third.
The first field is a time as
.Ic hh:mm ;
the second field either an
.Dq at
.Ql @\&
.Pq denoting no end time was given
or a time as
.Ic hh:mm .
The third field
.Pq if present
is a timezone name
.Pq see above .
.El
.It \(dg description
One or more lines prefixed by a tab character.
Together, they comprise the day description with the extended part removed.
Line breaks are the same as in the calendar file.
.El
.Pp
.Pa https://github.com/mirabilos/ev\-useful/tree/master/cal2ics
is a sample postprocessor converting this format to iCalendar (*.ics) format.
.Pp
The calendar file is preprocessed by
.Xr cpp 1 ,
allowing the inclusion of shared files such as company holidays or
meetings.
If the shared file is not referenced by a full pathname,
.Xr cpp 1
searches in the current (or home) directory first, and then in the
directory
.Pa /usr/share/calendar .
Empty lines and C comments
.Pq Li /* ...\& */
are ignored.
.Pp
Some possible calendar entries
(a \fB\et\fR sequence denotes a <tab> character):
.Bd -unfilled -offset indent
LANG=C
Easter=Ostern

#include <calendar.usholiday>
#include <calendar.birthday>

6/15\fB\et\fRJune 15 (if ambiguous, will default to month/day).
Jun.\& 15\fB\et\fRJune 15.
15 June\fB\et\fRJune 15.
Thursday\fB\et\fREvery Thursday.
June\fB\et\fREvery June 1st.
15 *\fB\et\fR15th of every month.

May Sun+2\fB\et\fRsecond Sunday in May (Muttertag)
04/SunLast\fB\et\fRlast Sunday in April,
\fB\et\fRsummer time in Europe
Easter\fB\et\fREaster
Ostern\-2\fB\et\fRGood Friday (2 days before Easter)
Paskha\fB\et\fROrthodox Easter
Advent+21\fB\et\fR4th Sunday of Advent
.Ed
.Sh FILES
.Bl -tag -width ~/.etc/calendar/calendar -compact
.It Pa calendar
File in current directory.
.It Pa ~/.etc/calendar
Directory in the user's home directory (which
.Nm
changes into, if it exists).
.It Pa ~/.etc/calendar/calendar
File to use if no
.Pa calendar
file exists in the current directory.
.It Pa ~/.etc/calendar/nomail
.Nm
will not mail if this file exists.
.It Pa calendar.all
International and national calendar files.
.It Pa calendar.birthday
Births and deaths of famous (and not-so-famous) people.
.It Pa calendar.christian
Christian holidays (should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year).
.It Pa calendar.computer
Computer people's days of special significance.
.It Pa calendar.croatian
Croatian calendar.
.It Pa calendar.fictional
Fantasy and fiction dates (mostly LOTR).
.It Pa calendar.french
French calendar.
.It Pa calendar.german
German calendar.
.It Pa calendar.history
Everything else, mostly U.S.\& historical events.
.It Pa calendar.holiday
Other holidays (including the not-well-known, obscure, and
.Em really
obscure).
.It Pa calendar.judaic
Jewish holidays (should be updated yearly by the local system administrator
so that roving holidays are set correctly for the current year).
.It Pa calendar.music
Musical events, births, and deaths (strongly oriented toward rock'n'roll).
.It Pa calendar.openbsd
.Ox
and
.Mx Ns -related
events.
.It Pa calendar.pagan
Pagan holidays, celebrations and festivals.
.It Pa calendar.russian
Russian calendar.
.It Pa calendar.usholiday
U.S.A.\& holidays.
.It Pa calendar.world
World wide calendar.
.El
.Sh SEE ALSO
.Xr at 1 ,
.Xr cal 1 ,
.Xr cpp 1 ,
.Xr mail 1 ,
.Xr cron 8
.Pp
The
.Pa evolvis.org
.Dq Li useful\-scripts
repository.
.Sh STANDARDS
The
.Nm
program previously selected lines which had the correct date anywhere
in the line.
This is no longer true: the date is only recognised when it occurs
at the beginning of a line.
.Sh HISTORY
A
.Nm
command appeared in
.At v7 .
.Pp
Since
.Mx 10 ,
if the
.Dv UNICODE
variable is set during compilation,
.Xr iconv 3
is used to convert any input to UTF-8 output.
.Pp
.Dv ANNIV
and
.Ic Advent
handling appeared in
.Mx 11 .
Other implementations silently ignore the field assignment,
so
.Dv ANNIV
is backwards-compatible.
.Sh BUGS
.Nm
doesn't handle all Jewish holidays or moon phases.
.Pp
The lunar calendar is recognised but not implemented.
